### PR TITLE
Add __gt__ and __lt__ overrides for TagBase.

### PR DESCRIPTION
**Pull request by adam-thomas**
Fixes an incompatibility with django-modelcluster and, by extension, Wagtail.

@incuna/backend review please? :)

### CODE REVIEW

**Comment by todd-dembrey** [comment]
How should this handle capitalisations?

currently  `'Zebra' < 'aardvark'`

**Comment by adam-thomas** [comment]
Lol.  I wasn't aware of that.  I don't have a particular intent either way.

**Comment by todd-dembrey** [comment]
I think that is reasonable. frontend my end up capitalising it all anyway at least we give them a list that looks reasonable.

**Comment by adam-thomas** [comment]
:+1:

**Comment by adam-thomas** [comment]
May I

**Comment by adam-thomas** [comment]
oh thanks :)

**Pull request merged**
